#!/usr/bin/env bash
#
# PreToolUse hook (Edit|Write). Blocks hand edits to generated files, which
# the mocks-drift / docs-drift CI jobs would reject anyway.
set -euo pipefail

file=$(jq -r '.tool_input.file_path // empty')
[ -n "$file" ] || exit 0

root=${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel)}
case "$file" in
"$root"/*) rel=${file#"$root"/} ;;
*) exit 0 ;;
esac

case "$rel" in
*/mocks/*.go)
	echo "BLOCKED: $rel is generated by mockery. Edit the interface (see .mockery.yaml) and run 'make mocks'." >&2
	exit 2
	;;
docs/swagger.json | docs/swagger.yaml)
	echo "BLOCKED: $rel is generated by swag. Edit the @-annotations and run 'make docs'." >&2
	exit 2
	;;
esac
