// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	store "github.com/akira-core/kube-state-graph/pkg/route/store"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockStore) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStore_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStore_Expecter) Close() *MockStore_Close_Call {
	return &MockStore_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStore_Close_Call) Run(run func()) *MockStore_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_Close_Call) Return(_a0 error) *MockStore_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_Close_Call) RunAndReturn(run func() error) *MockStore_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ClustersWithIngressIP provides a mock function with given fields: ctx, ip, t0, t1
func (_m *MockStore) ClustersWithIngressIP(ctx context.Context, ip string, t0 time.Time, t1 time.Time) ([]string, error) {
	ret := _m.Called(ctx, ip, t0, t1)

	if len(ret) == 0 {
		panic("no return value specified for ClustersWithIngressIP")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]string, error)); ok {
		return rf(ctx, ip, t0, t1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []string); ok {
		r0 = rf(ctx, ip, t0, t1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, ip, t0, t1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ClustersWithIngressIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClustersWithIngressIP'
type MockStore_ClustersWithIngressIP_Call struct {
	*mock.Call
}

// ClustersWithIngressIP is a helper method to define mock.On call
//   - ctx context.Context
//   - ip string
//   - t0 time.Time
//   - t1 time.Time
func (_e *MockStore_Expecter) ClustersWithIngressIP(ctx interface{}, ip interface{}, t0 interface{}, t1 interface{}) *MockStore_ClustersWithIngressIP_Call {
	return &MockStore_ClustersWithIngressIP_Call{Call: _e.mock.On("ClustersWithIngressIP", ctx, ip, t0, t1)}
}

func (_c *MockStore_ClustersWithIngressIP_Call) Run(run func(ctx context.Context, ip string, t0 time.Time, t1 time.Time)) *MockStore_ClustersWithIngressIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockStore_ClustersWithIngressIP_Call) Return(_a0 []string, _a1 error) *MockStore_ClustersWithIngressIP_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ClustersWithIngressIP_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]string, error)) *MockStore_ClustersWithIngressIP_Call {
	_c.Call.Return(run)
	return _c
}

// LoadTrafficWindow provides a mock function with given fields: ctx, cluster, ip, t0, t1
func (_m *MockStore) LoadTrafficWindow(ctx context.Context, cluster string, ip string, t0 time.Time, t1 time.Time) (store.TrafficWindow, error) {
	ret := _m.Called(ctx, cluster, ip, t0, t1)

	if len(ret) == 0 {
		panic("no return value specified for LoadTrafficWindow")
	}

	var r0 store.TrafficWindow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) (store.TrafficWindow, error)); ok {
		return rf(ctx, cluster, ip, t0, t1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) store.TrafficWindow); ok {
		r0 = rf(ctx, cluster, ip, t0, t1)
	} else {
		r0 = ret.Get(0).(store.TrafficWindow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, cluster, ip, t0, t1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_LoadTrafficWindow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadTrafficWindow'
type MockStore_LoadTrafficWindow_Call struct {
	*mock.Call
}

// LoadTrafficWindow is a helper method to define mock.On call
//   - ctx context.Context
//   - cluster string
//   - ip string
//   - t0 time.Time
//   - t1 time.Time
func (_e *MockStore_Expecter) LoadTrafficWindow(ctx interface{}, cluster interface{}, ip interface{}, t0 interface{}, t1 interface{}) *MockStore_LoadTrafficWindow_Call {
	return &MockStore_LoadTrafficWindow_Call{Call: _e.mock.On("LoadTrafficWindow", ctx, cluster, ip, t0, t1)}
}

func (_c *MockStore_LoadTrafficWindow_Call) Run(run func(ctx context.Context, cluster string, ip string, t0 time.Time, t1 time.Time)) *MockStore_LoadTrafficWindow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time), args[4].(time.Time))
	})
	return _c
}

func (_c *MockStore_LoadTrafficWindow_Call) Return(_a0 store.TrafficWindow, _a1 error) *MockStore_LoadTrafficWindow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_LoadTrafficWindow_Call) RunAndReturn(run func(context.Context, string, string, time.Time, time.Time) (store.TrafficWindow, error)) *MockStore_LoadTrafficWindow_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
